### Options and bindings

# Use the xterm-256color terminal
set -g default-terminal "xterm-256color"

# Apply Tc
set -ga terminal-overrides ",xterm-256color:Tc"

set -g history-limit 100000

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# auto window rename
setw -g automatic-rename

# C-d is the new C-b
set -g prefix C-d
# recursive bind
bind-key d send-prefix

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Vi copypaste mode
setw -g mode-keys vi
bind-key -Tcopy-mode-vi v send -X begin-selection
# X11 (requires xsel)
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -p && xsel -o -p | xsel -i -b"
# Wayland (requires wl-clipboard)
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"

# fix pane_current_path on new window and splits
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"


### Theming

set -g status-style bg=colour235,fg=colour136,default

# Window format
setw -g window-status-format " #{window_index} #{window_name} "
setw -g window-status-current-format " #{window_index}#{window_flags}#{window_name} "

# snazzy theme
setw -g window-status-style fg=colour244,bg=default,dim
setw -g window-status-current-style fg=colour7,bg=default,bright

# pane border
set -g pane-border-style fg=colour235
set -g pane-active-border-style fg=colour248

# message text
set -g message-style bg=default,fg=colour166

# pane number display
set -g display-panes-active-colour colour33
set -g display-panes-colour colour166
# clock
setw -g clock-mode-colour green

set -g status-interval 100
set -g status-justify left # center align window list
set -g status-left-length 20
set -g status-right-length 140
set -g status-left ''
set -g status-right '#[fg=colour244]mrota@#[fg=green]#H'
